### ISSUE TITLE
Feature: Support Enum

### ISSUE THREAD

**Issue by mr54ndm4n** [DreamN/Groot#10]
Support enum in methods
`public static IEnumerable<T> GetObjectFromCsv<T>(string filePath, bool autoMapForNoCustomAttr = true)`

➕  create a unit-test inside GrootUnitTest with code coverage >= 80% (you can see coverage report on pull request as well)

Comment if you want to take it.
Happy Hacktoberfest!

**Comment by mr54ndm4n** [comment]
### **Given:**
**csv**
Item.csv

    name, amount, type
    itema, 68, 1
    itemb, 42, 2
    itemc, 55, 1

**code**
```csharp
enum ItemType {Plastic=1, Wood=2, Iron=3, Fabric=4};
public class Item
 {
        [GrootField("name")]
        public string name { get; set; }
        [GrootField("amount")]
        public int Amount { get; set; }
        [GrootField("type")]
        public ItemType Type { get; set; }
  }
```

**Comment by itsjason** [comment]
Good morning! I will take a crack at this today.

**Comment by mr54ndm4n** [comment]
@itsjason Ok :)

**Comment by itsjason** [comment]
Oh no, I may have to back out of this. I didn't realize it was .NET Core, which I have 0 experience with. I will get set up for Core if I have time, but it may be a little while and someone else can feel free to take this as well.

**Comment by B1tF8er** [comment]
Can I take this?

**Comment by mr54ndm4n** [comment]
@itsjason No problem, thanks you :)
@B1tF8er Sure! you can take this.
